{% set name = "geodemora" %}
{% set version = "0.0.7" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 374a051bf976f05b862a9a148e972069f4409ed9375f71266339054c7bf906db

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - earthengine-api
    - folium
    - geopandas
    - ipyleaflet
    - numpy
    - pyshp
    - python >={{ python_min }}
    - rasterio

test:
  imports:
    - geodemora
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: "https://github.com/ramendra1990/geodemora"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "A python package for interactive mapping"
  doc_url: https://ramendra1990.github.io/geodemora/
  dev_url: https://github.com/ramendra1990/geodemora

extra:
  recipe-maintainers:
    - ramendra1990
